---
- name: Configure Ubuntu server
  hosts: servers
  become: yes

  roles:
    - docker
    - nginx
    - certbot
    - monitoring

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes


    - name: Install packages
      apt:
        name:
          - curl
          - neovim
          - htop
        state: present
